name: Event deploy

on:
  push:
    branches:
      - main

jobs:

  build_and_push_to_docker_hub:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/event:latest

  dispatch:
    needs: [build_and_push_to_docker_hub]
    runs-on: ubuntu-latest
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: "StAndUP-ru/funtech"
          event-type: update_remote
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "events", "branch": "develop"}'
